create table if not exists public.paid_reports (
  id bigint generated by default as identity primary key,
  payment_id text not null unique,
  order_id text not null,
  report_token text unique,
  email text not null,
  phone text not null,
  name text not null,
  amount integer not null check (amount >= 1),
  currency text not null check (currency in ('INR', 'USD')),
  report_data jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.paid_reports
  add column if not exists phone text;

alter table public.paid_reports
  add column if not exists order_id text;

alter table public.paid_reports
  add column if not exists report_token text;

notify pgrst, 'reload schema';

alter table public.paid_reports
  alter column report_data drop not null;

alter table public.paid_reports
  drop constraint if exists paid_reports_amount_check;

alter table public.paid_reports
  add constraint paid_reports_amount_check check (amount >= 1);

create index if not exists paid_reports_email_idx
  on public.paid_reports (email);

create unique index if not exists paid_reports_report_token_idx
  on public.paid_reports (report_token)
  where report_token is not null;

alter table public.paid_reports enable row level security;
