create table if not exists public.paid_reports (
  id bigint generated by default as identity primary key,
  payment_id text not null unique,
  order_id text not null,
  report_token text unique,
  email text not null,
  phone text not null,
  name text not null,
  amount integer not null check (amount >= 1),
  currency text not null check (currency in ('INR', 'USD')),
  report_data jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.paid_reports
  add column if not exists phone text;

alter table public.paid_reports
  add column if not exists order_id text;

alter table public.paid_reports
  add column if not exists report_token text;

alter table public.paid_reports
  add column if not exists visitor_id uuid;

alter table public.paid_reports
  add column if not exists career_question_used boolean not null default false;

notify pgrst, 'reload schema';

alter table public.paid_reports
  alter column report_data drop not null;

alter table public.paid_reports
  drop constraint if exists paid_reports_amount_check;

alter table public.paid_reports
  add constraint paid_reports_amount_check check (amount >= 1);

create index if not exists paid_reports_email_idx
  on public.paid_reports (email);

create index if not exists paid_reports_visitor_career_idx
  on public.paid_reports (visitor_id, career_question_used)
  where visitor_id is not null;

create unique index if not exists paid_reports_report_token_idx
  on public.paid_reports (report_token)
  where report_token is not null;

alter table public.paid_reports enable row level security;


create table if not exists love_astrologer_votes (
  id bigint generated always as identity primary key,
  voter_id text not null unique,
  created_at timestamptz not null default now()
);

alter table love_astrologer_votes enable row level security;

-- allow the server (service role) full access; no public policies needed
-- since all reads/writes go through your API route with the service key

-- seed with your existing count so the number doesn't reset to 0
insert into love_astrologer_votes (voter_id)
select 'seed-' || gs
from generate_series(1, 1316) as gs
on conflict (voter_id) do nothing;